### ISSUE TITLE
make sure data schemes are correct

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-client-go#49]
in looking through the models, I noticed one thing that seems incorrect:

https://github.com/vapor-ware/synse-client-go/blob/82943a5ece88be1df570d0e95fbfb8118f03fdc8/synse/scheme/info.go#L3-L19

in particular, the `metadata` should be a `map[string]string`, not its own type with expected fields -- the data in there is totally arbitrary.

I didn't notice anything else, but I'll take another pass through later and see if I notice anything.

--------

work items for this issue:

- [x] fix metadata in Info scheme
- [x] add "alias" to [info response](https://github.com/vapor-ware/synse-client-go/blob/7fde9bb5f12a3199778e6b5a68d612ad5bbd286d/synse/scheme/info.go#L4-L14) (see: [docs](https://synse.readthedocs.io/en/v3/server/api.v3/#info))
- [x] add "alias" to [scan](https://github.com/vapor-ware/synse-client-go/blob/7fde9bb5f12a3199778e6b5a68d612ad5bbd286d/synse/scheme/scan.go#L4-L10) response (see: [docs](https://synse.readthedocs.io/en/v3/server/api.v3/#scan))
- [x] update [Write scheme](https://github.com/vapor-ware/synse-client-go/blob/7fde9bb5f12a3199778e6b5a68d612ad5bbd286d/synse/scheme/write.go#L4-L9) (Transaction -> Id) (see: [docs](https://synse.readthedocs.io/en/v3/server/api.v3/#write-asynchronous))

**Comment by hoanhan101** [comment]
I am looking at the other 2 work items for this issue but not totally sure what parts of the documentation are these pointing to.

**Comment by edaniszewski** [comment]
updated the items with links! note that the docs being linked to are still under construction. The response JSON there should all be correct, but I'm still in the process of updating descriptions and such
