### ISSUE TITLE
fix ci falling on test

### ISSUE THREAD

**Issue by hoanhan101** [vapor-ware/synse-client-go#71]
in #70, according to @edaniszewski, ci has such failure on test:
```
+ CGO_ENABLED=0 go test -covermode=atomic ./...
go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache: permission denied
go: cannot use modules with build cache disabled
script returned exit code 1
```
@lazypower said it could be related to user permissions when using docker on host.

**Comment by lazypower** [comment]
Fixed as of https://build.vio.sh/blue/organizations/jenkins/vapor-ware%2Fsynse-client-go/detail/chuck%2Fpipeline/12/pipeline once https://github.com/vapor-ware/synse-client-go/pull/74 lands
